### ISSUE TITLE
Fetch projects using GitHub API

### ISSUE THREAD

**Issue by ppalone** [GCOEA-DEV/gdc-website#14]
- Use the GitHub api to fetch all of our public projects
- Display it on the React frontent

**Comment by jabo-bernardo** [comment]
I would like to work on this one

**Comment by Aashishkushwaha** [comment]
I'll take this up, can you please elaborate this issue?

**Comment by ppalone** [comment]
@Aashishkushwaha fetch all repos from teh GCOEA-DEV org and display it as a table on frontend.

**Comment by ppalone** [comment]
@jabo-bernardo Go ahead

**Comment by jabo-bernardo** [comment]
Awesome! On it

**Comment by jabo-bernardo** [comment]
Done 👍

**Comment by ppalone** [comment]
Thanks @jabo-bernardo
